idf_component_register(
    SRCS 
        "main.cpp"
        "../hal/hal_system_p4.cpp"
        "../hal/hal_display_p4.cpp"
        "../hal/hal_input_p4.cpp"
        "../hal/hal_audio_p4.cpp"
        "../hal/hal_network_p4.cpp"
        "../hal/hal_storage_p4.cpp"
        "../hal/hal_persistence_p4.cpp"
        "../hal/DisplayHAL.cpp"
        "../hal/TouchHAL.cpp"
        "../hal/AudioHAL.cpp"
        "../hal/LVGL_Port.cpp"
        "../hal/hal_flasher_p4.cpp"
        "../hal/usb_cdc_loader_port.cpp"
        "../hal/usb_device_manager.cpp"
        "../hal/hal_uart_p4.cpp"
        "../hal/hal_mesh_p4.cpp"
        "../hal/hal_radio_p4.cpp"
        "../hal/hal_http_p4.cpp"
        "../hal/hal_socket_p4.cpp"
        "../hal/hal_ssh_p4.cpp"
        "../hal/hal_hid_p4.cpp"
        "../hal/hal_lan_recon_p4.cpp"
        "../hal/EspIdfTimeProvider.cpp"
    INCLUDE_DIRS 
        "."
        "../hal"
    REQUIRES 
        "core"
        "skuodi__libssh2_esp"
        "esp_driver_i2c"
        "esp_driver_i2s"
        "esp_driver_gpio"
        "esp_driver_uart"
        "esp_driver_ledc"
        "esp_driver_ppa"
        "esp_driver_tsens"
        "esp_lcd"
        "espressif__esp_lcd_st7701"
        "espressif__esp_lcd_touch"
        "espressif__esp_lcd_touch_gt911"
        "espressif__esp_codec_dev"
        "espressif__esp_lvgl_port"
        "espressif__esp-serial-flasher"
        "espressif__usb_host_cdc_acm"
        "espressif__esp_tinyusb"
        "usb"
        "lvgl__lvgl"
        "esp_driver_sdmmc"
        "sdmmc"
        "fatfs"
        "spiffs"
        "vfs"
        "esp_wifi"
        "esp_netif"
        "esp_event"
        "driver"
        "nvs_flash"
        "esp_timer"
        "esp_partition"
        "app_update"
        "spi_flash"
        "esp_mm"
        "freertos"
    WHOLE_ARCHIVE
)

