[platformio]
default_envs = esp32s3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = jc3248w535
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_speed = 921600
monitor_speed = 115200
upload_flags =
    --before=usb_reset
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.partitions = custom_16MB_ota.csv
build_flags =
    -I include
    -Wall
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SUPPORT=1
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -DCONFIG_SPIRAM_TYPE_AUTO=1
    -DCONFIG_SPIRAM_SIZE=8388608
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
    -O2

[env:esp32s3]
build_src_filter =
    +<**/*.cpp>
    +<**/*.c>
    +<../hal/*.cpp>
    -<DoomLauncher.cpp>
    -<GBCLauncher.cpp>
    -<LuaLauncher.cpp>
    -<CartridgeGamepad.cpp>
    -<esp_lcd_*.c>

build_flags =
    ${env.build_flags}
    -I hal
    -I ../../core/include
    -I ../../core/src/tts
    -I ../../core/src/tts/picotts
    -I ../../core/src/tts/picotts/lib
    -I ../../core/src/ui
    -I ../../core/src/ui/views
    -I ../../core/src/ui/views/utilities
    -I ../../core/src/ui/components/terminal
    -I ../../core/src/ui/modals
    -I ../../core/src/terminal
    -I ../../core/src/cartridge
    -I ../../core/src/meshcore
    -I ../../core/src/audio
    -I ../../core/src/audio/libhelix/src
    -I ../../core/src/audio/libhelix/src/libhelix-mp3
    -I ../../core/src/audio/libhelix/src/libhelix-aac
    -I ../../core/src/lua
    -I ../../core/src/lua/liblua
    -DLV_USE_SDL=0
    -DESP32
    -DUSE_DEFAULT_STDLIB
    -DHELIX_LOGGING_ACTIVE=0
    -DARDUINO_LOOP_STACK_SIZE=32768
    -DLUA_32BITS
    -include string.h
    -Wl,--defsym=_binary_app_recorder_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_recorder_bin_start
    -Wl,--defsym=_binary_app_radio_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_radio_bin_start
    -Wl,--defsym=_binary_app_browser_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_browser_bin_start
    -Wl,--defsym=_binary_app_terminal_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_terminal_bin_start
    -Wl,--defsym=_binary_app_cartridge_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_cartridge_bin_start
    -Wl,--defsym=_binary_app_lua_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_lua_bin_start
    -Wl,--defsym=_binary_app_editor_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_editor_bin_start
    -Wl,--defsym=_binary_app_utilities_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_utilities_bin_start
    -Wl,--defsym=_binary_app_gallery_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_gallery_bin_start
    -Wl,--defsym=_binary_app_files_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_files_bin_start
    -Wl,--defsym=_binary_app_music_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_music_bin_start
    -Wl,--defsym=_binary_app_flasher_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_flasher_bin_start
    -Wl,--defsym=_binary_app_config_bin_start=_binary__home_kaber420_Documentos_proyectos_cbdos_core_assets_icons_app_config_bin_start
board_build.embed_txtfiles =
    ../../core/assets/icons/app_recorder.bin
    ../../core/assets/icons/app_radio.bin
    ../../core/assets/icons/app_browser.bin
    ../../core/assets/icons/app_terminal.bin
    ../../core/assets/icons/app_cartridge.bin
    ../../core/assets/icons/app_lua.bin
    ../../core/assets/icons/app_editor.bin
    ../../core/assets/icons/app_utilities.bin
    ../../core/assets/icons/app_gallery.bin
    ../../core/assets/icons/app_files.bin
    ../../core/assets/icons/app_music.bin
    ../../core/assets/icons/app_flasher.bin
    ../../core/assets/icons/app_config.bin

lib_deps =
    lvgl/lvgl@^9.5.0
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/me-processware/JC3248W535-Driver.git
    ewpa/LibSSH-ESP32 @ ^5.9.0
    SPIFFS
    FS
    SD
    SPI
    symlink://../../core

[env:gbc]
build_src_filter =
    -<**/*>
    +<GBCLauncher.cpp>
    +<CartridgeGamepad.cpp>
    +<esp_lcd_*.c>
lib_deps =
    https://github.com/me-processware/JC3248W535-Driver.git
    tamctec/TAMC_GT911@^1.0.2
    SD
    SPI
    SPIFFS
build_flags =
    ${env.build_flags}
    -O3
    -fomit-frame-pointer
    -funroll-loops
    -finline-functions
    -ffast-math
    -I lib/peanut_gb
    -DENABLE_LCD=1
    -DENABLE_SOUND=1
    -DWALNUT_GB_HIGH_LCD_ACCURACY=0
    -DWALNUT_GB_USE_INTRINSICS=1
    -DMINIGB_APU_AUDIO_FORMAT_S16SYS=1
    -DAUDIO_SAMPLE_RATE=32768
    -DARDUINO_LOOP_STACK_SIZE=32768
    -DI2S_BCLK=42
    -DI2S_LRC=2
    -DI2S_DOUT=41
upload_command = "$PYTHONEXE" "$PROJECT_PACKAGES_DIR/tool-esptoolpy/esptool.py" --chip esp32s3 --port $UPLOAD_PORT --baud 921600 write_flash 0x910000 $SOURCE

[env:doom]
build_src_filter =
    -<**/*>
    +<DoomLauncher.cpp>
    +<CartridgeGamepad.cpp>
    +<esp_lcd_*.c>
lib_deps =
    https://github.com/me-processware/JC3248W535-Driver.git
    tamctec/TAMC_GT911@^1.0.2
    SD
    SPI
    SPIFFS
build_flags =
    ${env.build_flags}
    -I lib/doomgeneric
    -DDOOMGENERIC_RESX=320
    -DDOOMGENERIC_RESY=200
    -DFILES_DIR=\"/sd\"
    -DARDUINO_LOOP_STACK_SIZE=32768
    -DFEATURE_SOUND=1
    -DI2S_BCLK=42
    -DI2S_LRC=2
    -DI2S_DOUT=41
upload_command = "$PYTHONEXE" "$PROJECT_PACKAGES_DIR/tool-esptoolpy/esptool.py" --chip esp32s3 --port $UPLOAD_PORT --baud 921600 write_flash 0x510000 $SOURCE

[env:lua]
build_src_filter =
    -<**/*>
    +<LuaLauncher.cpp>
    +<esp_lcd_*.c>
lib_deps =
    https://github.com/me-processware/JC3248W535-Driver.git
    tamctec/TAMC_GT911@^1.0.2
    SD
    SPI
    SPIFFS
    symlink://../../core/src/lua/liblua
    symlink://../../cartridges/common_lua_engine
build_flags =
    ${env.build_flags}
    -I ../../cartridges/common_lua_engine
    -I ../../cartridges/common_lua_engine/shared
    -I ../../cartridges/common_lua_engine/lua_core
    -I ../../cartridges/common_lua_engine/pico8
    -I ../../cartridges/common_lua_engine/cbd_engine
    -I ../../core/src/lua/liblua
    -DLUA_USE_C89
    -DARDUINO_LOOP_STACK_SIZE=32768
upload_command = "$PYTHONEXE" "$PROJECT_PACKAGES_DIR/tool-esptoolpy/esptool.py" --chip esp32s3 --port $UPLOAD_PORT --baud 921600 write_flash 0x510000 $SOURCE


