[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = jc3248w535
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_speed = 921600
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.partitions = custom_16MB_ota.csv

build_src_filter =
    +<**/*.cpp>
    +<**/*.c>
    +<../hal/*.cpp>

build_flags =
    -I include
    -I hal
    -I ../../core/include
    -I ../../core/src/ui
    -I ../../core/src/audio
    -I ../../core/src/audio/libhelix/src
    -I ../../core/src/audio/libhelix/src/utils
    -I ../../core/src/audio/libhelix/src/libhelix-mp3
    -I ../../core/src/audio/libhelix/src/libhelix-aac
    -I ../../core/src/lua
    -I ../../core/src/lua/liblua
    -Wall
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SUPPORT=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_USE_SDL=0
    -DESP32
    -DUSE_DEFAULT_STDLIB
    -DHELIX_LOGGING_ACTIVE=0
    -O2

lib_deps =
    lvgl/lvgl@^9.5.0
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/me-processware/JC3248W535-Driver.git
    symlink://../../core
