// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/cdtc.py from jc3248w535.json
// Board: JC3248W535 (v1.0) - SoC: esp32s3

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace cbdos {
namespace board {

// 0. Informacion General de Placa
constexpr const char* BOARD_NAME = "JC3248W535";
constexpr const char* BOARD_VERSION = "1.0";
constexpr const char* SOC_TYPE = "esp32s3";

// Pines de expansion disponibles (Cabecera JP1 Whitelist)
constexpr size_t NUM_EXPANSION_PINS = 8;
constexpr std::array<int, NUM_EXPANSION_PINS> EXPANSION_PINS = {
    5, 6, 7, 9, 14, 17, 18, 38
};

// Pines asignados a perifericos del sistema base
constexpr size_t NUM_SYSTEM_PINS = 23;
constexpr std::array<int, NUM_SYSTEM_PINS> SYSTEM_PINS = {
    1, 2, 3, 4, 8, 10, 11, 12, 13, 15, 16, 19, 20, 21, 39, 40, 41, 42, 43, 44, 45, 47, 48
};

// Pines estrictamente prohibidos (Flash/PSRAM OPI)
constexpr size_t NUM_PROHIBITED_PINS = 12;
constexpr std::array<int, NUM_PROHIBITED_PINS> PROHIBITED_PINS = {
    26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37
};

// 1. Pantalla
namespace display {
    constexpr const char* DRIVER = "axs15231b";
    constexpr const char* BUS = "qspi";
    constexpr int WIDTH = 320;
    constexpr int HEIGHT = 480;
    constexpr int FPS = 30;
    constexpr int PIN_RST = -1;
    constexpr int PIN_BL = 1;
    // Pines bus QSPI (si aplica)
    constexpr int PIN_CS = 45;
    constexpr int PIN_SCLK = 47;
    constexpr int PIN_D0 = 21;
    constexpr int PIN_D1 = 48;
    constexpr int PIN_D2 = 40;
    constexpr int PIN_D3 = 39;
}

// 2. Touchscreen (I2C)
namespace touch {
    constexpr int PIN_SDA = 4;
    constexpr int PIN_SCL = 8;
    constexpr int PIN_RST = -1;
    constexpr int PIN_INT = 3;
    constexpr int I2C_PORT = 0;
    constexpr uint32_t I2C_FREQ = 400000;
    constexpr uint8_t I2C_ADDR = 0x3B;
}

// 3. Audio (I2S + Codec)
namespace audio {
    constexpr bool HAS_MCLK = false;
    constexpr int PIN_MCLK = -1;
    constexpr int PIN_BCLK = 42;
    constexpr int PIN_WS = 2;
    constexpr int PIN_DOUT = 41;
    constexpr int PIN_DIN = -1;
    constexpr int PIN_PA = -1;
}

// 4. Tarjeta MicroSD (SDMMC / SPI)
namespace sdcard {
    constexpr const char* BUS = "spi";
    // Pines SDMMC
    constexpr int PIN_D0 = 13;
    constexpr int PIN_D1 = -1;
    constexpr int PIN_D2 = -1;
    constexpr int PIN_D3 = -1;
    constexpr int PIN_CLK = 12;
    constexpr int PIN_CMD = 11;
    // Pines SPI
    constexpr int PIN_CS = 10;
    constexpr int PIN_MOSI = 11;
    constexpr int PIN_SCK = 12;
    constexpr int PIN_MISO = 13;
}

// 5. Consola Serie (UART0) & USB Nativo
namespace console {
    constexpr int PIN_TX = 43;
    constexpr int PIN_RX = 44;
    constexpr int PIN_USB_DM = 19;
    constexpr int PIN_USB_DP = 20;
}

// 6. Flasher Externo
namespace flasher {
    constexpr int PIN_TX = 15;
    constexpr int PIN_RX = 16;
}

// 7. Coprocesador ESP32-C6 (SDIO)
namespace coprocessor {
    constexpr bool HAS_COPROCESSOR = false;
    constexpr size_t NUM_SDIO_PINS = 0;
    constexpr std::array<int, NUM_SDIO_PINS> PINS_SDIO = {};
    constexpr int PIN_RESET = -1;
    constexpr int PIN_HANDSHAKE = -1;
}

// 8. Sensores
namespace sensors {
    constexpr int PIN_BATTERY_ADC = -1;
}

// 9. Botones Fisicos
namespace buttons {
    constexpr int PIN_BOOT = -1;
}

} // namespace board
} // namespace cbdos
